import Sidebar from "@/components/layouts/sidebar/Sidebar";
import "./globals.css";
import { Inter } from "next/font/google";
import Followbar from "@/components/layouts/Followbar";
import Modal from "@/components/Modal/Modal";
import LoginModal from "@/components/Modal/LoginModal";
import RegisterModal from "@/components/Modal/RegisterModal";
import ToasterProvider from "@/providers/ToasterProvider";
import getCurrentUser from "@/libs/serverAuth";
import { User } from "@prisma/client";
import { getUsers } from "@/libs/users";
import EditModal from "@/components/Modal/EditModal";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Twitter",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser: User | null = await getCurrentUser(); 
  const users = await getUsers(); 
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
        <ToasterProvider />
          {/* <Modal isOpen title="hello" actionLabel="submit" /> */}
          <EditModal currentUser={currentUser} />
          <LoginModal  />
          <RegisterModal />


          <div className="h-screen bg-black">
            <div className="container h-full mx-auto xl:px-30 max-w-6xl">
              <div className="grid grid-cols-4 h-full">
              
              
                <Sidebar currentUser={currentUser} />
                <div className="col-span-3 lg:col-span-2 border-neutral-800 ">
                  {children}
                </div>
             
                <Followbar users={users} />
              </div>
            </div>
          </div>
        </>
      </body>
    </html>
  );
}
