import Sidebar from "@/components/layouts/sidebar/Sidebar";
import "./globals.css";
import { Inter } from "next/font/google";
import Followbar from "@/components/layouts/Followbar";
import Modal from "@/components/Modal/Modal";
import LoginModal from "@/components/Modal/LoginModal";
import RegisterModal from "@/components/Modal/RegisterModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Twitter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          {/* <Modal isOpen title="hello" actionLabel="submit" /> */}
          <LoginModal />
          <RegisterModal />

          <div className="h-screen bg-black">
            <div className="container h-full mx-auto xl:px-30 max-w-6xl">
              <div className="grid grid-cols-4 h-full">
                <Sidebar />
                <div className="col-span-3 lg:col-span-2 border-neutral-800 ">
                  {children}
                </div>
                <Followbar />
              </div>
            </div>
          </div>
        </>
      </body>
    </html>
  );
}
